# Métodos matemátidos para físicos I

## Tensores, autovectores y autovalores

Autores:
- Nicolás Toledo Parra, 2200017
- Gabriela Sánchez Ariza, 22000816

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
datos = pd.read_csv('datosmasas.csv')

In [3]:
datos

particula  masas       x       y      z
0             1    2.0   -53.0    79.0  -91.0
1             2    2.0    13.0  -142.0 -177.0
2             3    2.0  -109.0  -103.0 -120.0
3             4    2.0     4.0   -96.0  110.0
4             5    4.0   222.0   -22.0 -236.0
...         ...    ...     ...     ...    ...
1528       1529    3.0  1646.0  1612.0  -30.0
1529       1530    2.0  1610.0  1650.0 -145.0
1530       1531    5.0  1626.0  1537.0   96.0
1531       1532    2.0  1390.0  1480.0  160.0
1532       1533    2.0  1717.0  1464.0  -59.0

[1533 rows x 5 columns]

## 1. a) [Caso 2D]

#### 1: Masa total del sistema

In [4]:
momento0 = datos.sum(axis=0)
print(momento0)
M = 4627.0

particula    1175811.0
masas           4627.0
x            1260086.0
y            1189409.0
z              23092.0
dtype: float64


#### 2: Centro masa

In [5]:
dfmasas = datos['masas']
dfx = datos['x']
dfy = datos['y']
dfz = datos['z']

In [6]:
sumax, sumay = 0, 0

for i in range(0,1533,1):
    m = dfmasas.iloc[i]
    x = dfx.iloc[i]
    y = dfy.iloc[i]

    sumax = m*x + sumax
    sumay = m*y + sumay

centromasaX = sumax / M
centromasaY = sumay / M

print(centromasaX, centromasaY)

825.8152150421439 776.9185217203371


#### 3: Tensor momento de inercia

In [7]:
Ixx, Ixy, Iyx, Iyy = 0, 0, 0, 0

for i in range(0, 1533, 1):
    m = dfmasas.iloc[i]
    x = dfx.iloc[i]
    y = dfy.iloc[i]
        
    Ixx = m*(y**2) + Ixx
    Ixy = m*(x*y) + Ixy
    Iyx = m*(x*y) + Iyx
    Iyy = m*(x**2) + Iyy

print(Ixx, Ixy, Iyx, Iyy)

3756528404.0 3880390098.0 3880390098.0 4114014339.0


In [8]:
TI = np.matrix([['Ixx', 'Ixy'], ['Iyx', 'Iyy']])
print(TI)
TensorInercia = np.matrix([[np.format_float_positional(Ixx, trim='-'), np.format_float_positional(-Ixy, trim='-')], [np.format_float_positional(-Iyx, trim='-'), np.format_float_positional(Iyy, trim='-')]])
print(TensorInercia)
TensorInercia = np.matrix([[np.format_float_positional(Ixx, trim='-'), np.format_float_positional(-Ixy, trim='-')], [np.format_float_positional(-Iyx, trim='-'), np.format_float_positional(Iyy, trim='-')]], dtype=float)


[['Ixx' 'Ixy']
 ['Iyx' 'Iyy']]
[['3756528404' '-3880390098']
 ['-3880390098' '4114014339']]


In [9]:
eigenvalores, eigenvectores = np.linalg.eig(TensorInercia)
print(eigenvalores)
print(eigenvectores)

[5.07667234e+07 7.81977602e+09]
[[-0.72319235  0.69064667]
 [-0.69064667 -0.72319235]]


In [10]:
np.dot([-0.72319235, -0.69064667], [-0.72319235, -0.69064667])

0.9999999978806116

In [11]:
eigenvectores_inv = np.linalg.inv(eigenvectores)
eigenvectores_inv

matrix([[-0.72319235, -0.69064667],
        [ 0.69064667, -0.72319235]])

In [12]:
diagonalmatrix = np.matmul(eigenvectores_inv, (np.matmul(TensorInercia, eigenvectores)))
diagonalmatrix

matrix([[5.07667234e+07, 0.00000000e+00],
        [3.12924385e-07, 7.81977602e+09]])

In [13]:
np.matmul(eigenvectores, (np.matmul(diagonalmatrix, eigenvectores_inv)))

matrix([[ 3.75652840e+09, -3.88039010e+09],
        [-3.88039010e+09,  4.11401434e+09]])

## b) [Caso 3D]

#### 1: Masa total del sistema

In [14]:
momento0 = datos.sum(axis=0)
print(momento0)
M = 4627.0

particula    1175811.0
masas           4627.0
x            1260086.0
y            1189409.0
z              23092.0
dtype: float64


#### 2: Centro masa

In [15]:
sumax, sumay, sumaz = 0, 0, 0

for i in range(0,1533,1):
    m = dfmasas.iloc[i]
    x = dfx.iloc[i]
    y = dfy.iloc[i]
    z = dfz.iloc[i]


    sumax = m*x + sumax
    sumay = m*y + sumay
    sumaz = m*z + sumaz

centromasaX = sumax / M
centromasaY = sumay / M
centromasaZ = sumaz / M

print(centromasaX, centromasaY, centromasaZ)

825.8152150421439 776.9185217203371 15.503349902744759


#### 3: Tensor de inercia

In [16]:
Ixx, Ixy, Ixz, Iyx, Iyy, Iyz, Izx, Izy, Izz = 0, 0, 0, 0, 0, 0, 0, 0, 0

for i in range(0, 1533, 1):
    m = dfmasas.iloc[i]
    x = dfx.iloc[i]
    y = dfy.iloc[i]
    z = dfz.iloc[i]
        
    Ixx = m*(y**2 + z**2) + Ixx
    Ixy = m*(x*y) + Ixy
    Ixz = m*(x*z) + Ixz
    Iyx = m*(x*y) + Iyx
    Iyy = m*(x**2 + z**2) + Iyy
    Iyz = m*(y*z) + Iyz
    Izx = m*(x*z) + Izx
    Izy = m*(y*z) + Izy
    Izz = m*(x**2 + y**2) + Izz
    

print(Ixx, Ixy, Ixz, Iyx, Iyy, Iyz, Izx, Izy, Izz)

3859483842.0 3880390098.0 52096980.0 3880390098.0 4216969777.0 53801876.0 52096980.0 53801876.0 7870542743.0


In [17]:
TI = np.matrix([['Ixx', 'Ixy', 'Ixz'], ['Iyx', 'Iyy', 'Iyz'], ['Izx', 'Izy', 'Izz']])
print(TI)
TensorInercia = np.matrix([[np.format_float_positional(Ixx, trim='-'), np.format_float_positional(-Ixy, trim='-'), np.format_float_positional(-Ixz, trim='-')], [np.format_float_positional(-Iyx, trim='-'), np.format_float_positional(Iyy, trim='-'), np.format_float_positional(-Iyz, trim='-')], [np.format_float_positional(-Izx, trim='-'), np.format_float_positional(-Izy, trim='-'), np.format_float_positional(Izz, trim='-')]])
print(TensorInercia)
TensorInercia = np.matrix([[np.format_float_positional(Ixx, trim='-'), np.format_float_positional(-Ixy, trim='-'), np.format_float_positional(-Ixz, trim='-')], [np.format_float_positional(-Iyx, trim='-'), np.format_float_positional(Iyy, trim='-'), np.format_float_positional(-Iyz, trim='-')], [np.format_float_positional(-Izx, trim='-'), np.format_float_positional(-Izy, trim='-'), np.format_float_positional(Izz, trim='-')]], dtype=float)


[['Ixx' 'Ixy' 'Ixz']
 ['Iyx' 'Iyy' 'Iyz']
 ['Izx' 'Izy' 'Izz']]
[['3859483842' '-3880390098' '-52096980']
 ['-3880390098' '4216969777' '-53801876']
 ['-52096980' '-53801876' '7870542743']]


In [18]:
eigenvalores, eigenvectores = np.linalg.eig(TensorInercia)
print(eigenvalores)
print(eigenvectores)

[1.52996521e+08 7.92289755e+09 7.87110229e+09]
[[-0.72315583 -0.68914397 -0.04611112]
 [-0.69061685  0.72240857  0.03426699]
 [-0.00969618 -0.05662549  0.9983484 ]]


In [19]:
#np.dot([8.04932981e-01, -4.19572935e-01, -4.19572935e-01] , [,] , [,])
np.dot([8.04932981e-01, -4.19572935e-01, -4.19572935e-01] , [8.04932981e-01, -4.19572935e-01, -4.19572935e-01])


0.9999999994705748

In [20]:
eigenvectores_inv = np.linalg.inv(eigenvectores)
eigenvectores_inv

matrix([[-0.72315583, -0.69061685, -0.00969618],
        [-0.68914397,  0.72240857, -0.05662549],
        [-0.04611112,  0.03426699,  0.9983484 ]])

In [21]:
diagonalmatrix = np.matmul(eigenvectores_inv, (np.matmul(TensorInercia, eigenvectores)))
diagonalmatrix

matrix([[ 1.52996521e+08,  7.37108084e-07,  8.17825193e-08],
        [-9.42013844e-07,  7.92289755e+09,  9.74206967e-08],
        [-7.46617128e-08,  8.43064059e-08,  7.87110229e+09]])

In [22]:
np.matmul(eigenvectores, (np.matmul(diagonalmatrix, eigenvectores_inv)))

matrix([[ 3.85948384e+09, -3.88039010e+09, -5.20969800e+07],
        [-3.88039010e+09,  4.21696978e+09, -5.38018760e+07],
        [-5.20969800e+07, -5.38018760e+07,  7.87054274e+09]])